import "./globals.css";
import Footer from "../components/footer/Footer";
import Header from "@/components/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet" />
      </head>
      <body >
         <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
};
